### PR TITLE
Update cycle sort

### PR DESCRIPTION
**Pull request by yanurag1414**

### CODE REVIEW

**Review by lilmistake — APPROVED** [review]

**Comment by lilmistake** [comment]
The solution seems correct. Please remove the other 2 files and I'll merge it.
Thanks for contributing!

**Comment by yanurag1414** [comment]
Removed other two files

**Comment by lilmistake** [comment]
You accidentally deleted the solution.

**Comment by lilmistake** [comment]
Closing because a new PR has been created by the same user for the same issue (https://github.com/Chitresh-code/DSA_Worksheet/pull/46)

**Pull request closed without merging**
