### PR TITLE
Count Sort

### PR DESCRIPTION
**Pull request by AiyushKumar07**

### CODE REVIEW

**Comment by AiyushKumar07** [comment]
@lilmistake Kindly merge the My CountSort

**Review by lilmistake — CHANGES_REQUESTED** [review]
The CountSort solution doesn't pass all test cases, please correct that and try again.
Happy Coding!

**Comment by AiyushKumar07** [comment]
@lilmistake Kindly check and update me through which Test Case Failed...!! Thanks for your valuable time

**Comment by lilmistake** [comment]
The solution still doesn't work for negative numbers :(

**Comment by AiyushKumar07** [comment]
@lilmistake Sorry for inconvenience but "counting sort is incapable of sorting negative numbers"

**Comment by lilmistake** [comment]
Please refer to the link you submitted for the issue: https://leetcode.com/problems/sort-an-array/

**Comment by lilmistake** [comment]
PR moved to https://github.com/Chitresh-code/DSA_Worksheet/pull/93

**Pull request closed without merging**
