### PR TITLE
Create remove_node.java

### PR DESCRIPTION
**Pull request by gitaditee**

### CODE REVIEW

**Comment by Chitresh-code** [comment]
@gitaditee Again you have placed the file in the wrong directory, the pull request won't be merged until you fix it.

**Comment by gitaditee** [comment]
Can you send me the directory I'm not getting it

**Comment by Chitresh-code** [comment]
Sure @gitaditee,
Add the file in DSA_Codeheet/Java
There is a particular directory for every coding language, you just have to copy your file and paste it there.
Refer [this](https://github.com/Chitresh-code/DSA_Worksheet/blob/main/CONTRIBUTING.md#guidelines-for-contributions) for more info, it has all the info on how to do it properly.

**Comment by gitaditee** [comment]
I have done can you check the please!

**Comment by lilmistake** [comment]
Duplicate of https://github.com/Chitresh-code/DSA_Worksheet/pull/13

**Pull request closed without merging**
